######################################################################
#
# File name : SevenSeg_Top_wave.do
# Created on: Tue Nov 20 13:14:14 -0500 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
