######################################################################
#
# File name : SevenSeg_Top_compile.do
# Created on: Sat Dec 08 20:15:34 -0500 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xil_defaultlib  \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/ALU.vhd" \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/Data_Memory.vhd" \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/Hex2LED.vhd" \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/Instruction_Memory.vhd" \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/Program_Counter.vhd" \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/Register_File.vhd" \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/control_unit.vhd" \
"../../../../MIPS_Processor_REV_2.srcs/sources_1/new/MIPS_topModule.vhd" \


quit -force

