######################################################################
#
# File name : SevenSeg_Top_simulate.do
# Created on: Sat Dec 08 20:15:35 -0500 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.SevenSeg_Top

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {SevenSeg_Top_wave.do}

view wave
view structure
view signals

do {SevenSeg_Top.udo}

run 1000ns
