######################################################################
#
# File name : SevenSeg_Top_compile.do
# Created on: Mon Nov 26 18:17:33 -0500 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlog -64 -incr -work xil_defaultlib  \
"SevenSeg_Top_time_impl.v" \


quit -force

