######################################################################
#
# File name : SevenSeg_Top_wave.do
# Created on: Wed Nov 21 02:12:32 -0500 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
